### ISSUE TITLE
Problème pour saisir un résultat

### ISSUE THREAD

**Issue by flanker1** [johanpoirier/bet4soccer#12]
Lors de la saisie d'un résultat, seul 1 des 2 scores est pris en compte 
![image](https://cloud.githubusercontent.com/assets/14201181/15114755/c4959526-15fb-11e6-888a-b3dc36aaf45f.png)
![image](https://cloud.githubusercontent.com/assets/14201181/15114769/d12084ae-15fb-11e6-8cea-4390ba95a329.png)

Il faut s'y reprendre à 2 fois pour rentrer un score.

OS : Windows 10 Professionnel 64 bits
Navigateur : Chrome Version 50.0.2661.94 m

**Comment by johanpoirier** [comment]
J'ai changé techniquement l'enregistrement "live" des scores : tu pourras réitérer tes tests ?

**Comment by johanpoirier** [comment]
Normalement c'est bon.
