### ISSUE TITLE
Affichage onglets Mes pronostics vs Résultats

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#14]
Taille des cadres non cohérents entre ces 2 onglets
Taille de police des classements à droite plus petite dans l'onglet Résultats, du fait que le cadre est moins large
Possible de modifier l'onglet Résultats de façon à avoir les mêmes largeurs de cadre et taille de police ?

**Comment by johanpoirier** [comment]
J'ai corrigé l'affichage des classements.
Je ne toucherai pas à la largeur des cadres car cela sert à pourvoir s'adapter au contenu et à la largeur des écrans.
