### ISSUE TITLE
Erreur affichage classement

### ISSUE THREAD

**Issue by flanker1** [johanpoirier/bet4soccer#17]
![image](https://cloud.githubusercontent.com/assets/14201181/15145186/6e7345f8-16b4-11e6-9a21-c6e307d688ea.png)
Manque les points et le Rang pour Sylvain

**Comment by johanpoirier** [comment]
En fait non, je viens de vérifier car ça m'intriguait mais on avait fixé un ratio ```(nb pronos) / (nb matchs) > 0.6```.

Ce ratio est configurable pour le classement joueur et le classement groupe.
