### ISSUE TITLE
Management des pronostiqueurs

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#3]
Onglet Joueurs

Activer la modification des infos de chaque joueur en ligne
Lorsqu'on clique sur la ligne d'un joueur, il serait bien de pouvoir accéder aux données voire de les modifier

**Comment by johanpoirier** [comment]
En fait c'est déjà le cas, mais là tous les joueurs sont pas listés en haut car ils n'ont pas voté.
C'est assez bizarre, donc y'a un bug mais la fonctionnalité d'édition existe déjà.
