### ISSUE TITLE
Permettre de "rester connecter"

### ISSUE THREAD

**Issue by miralouche** [johanpoirier/bet4soccer#39]
Bonjour Johan & Cyril,

Serait-il possible d'avoir un bouton à cocher ou non "Rester connecter" ... histoire de ne pas avoir à rentrer le mot de passe à chaque visite.

C'est vraiment pas indispensable !
Merci pour le site et tout et tout.

A+

Bruno

**Comment by johanpoirier** [comment]
Ça doit être bon. A tester sur le long terme.
Une fois l'option cochée, on doit rester connecté 1 an sur le même appareil.
