### ISSUE TITLE
Jour matches phase finale

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#45]
Ajouter lundi/mardi/... à la date des matches de la phase finale

**Comment by johanpoirier** [comment]
où ? sur la page des pronos ?

**Comment by glideblue7** [comment]
oui Mes pronos et Resultats

Je constate que tu l'as fait, merci

2016-06-22 13:41 GMT+02:00 Johan Poirier <notifications@github.com>:
