### ISSUE TITLE
Accès phase finale autres pronostiqueurs (admin)

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#46]
##Lorsque l'on clique sur le nom d'un pronostiqueur dans le classement, on accède à ses pronostics de la phase de poules, si l'on clique ensuite sur Phase finale, on retombe sur nos propres pronostics de la phase finale et non ceux du pronostiqueur en question

Lien à corriger

En bidouillant sur l'adresse du lien, je peux accéder à ce que je souhaite mais cela est fastidieux.

De plus, la page s'appelle Ma phase finale alors qu'il s'agit de celle de l'autre pronostiqueur, donc le titre de la page est à corriger également : "Phase finale de X Y"

**Comment by johanpoirier** [comment]
Le lien emmène bien sur la phase finale du joueur, seul le titre est erroné.
