### ISSUE TITLE
Surligner les matches à venir dans la phase finale

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#47]
L'affichage de la phase finale se présentant sous un tableau, les matches ne sont pas forcément dans l'ordre chronologique et les prochains matches à venir ne sautent pas aux yeux.

Ainsi, si facilement implémentable, je propose : 
 - soit une option d'affichage par ordre chronologique (cela supprimerait totalement le tableau, affichage type phase de poules)
 - soit un surlignage (eu jaune, clignotement, en gras) de la date des matches à venir, càd de tous les matches du prochain jour de compétition

Ce n'est qu'une idée, j'ai conscience que cela ne doit pas être forcément aisé à programmer, donc ça peut ne pas se faire ;-)

**Comment by johanpoirier** [comment]
Les matchs qui auront lieu dans moins de 36h s'afficheront en gras. Ça te va ?

**Comment by glideblue7** [comment]
Très bien
