### ISSUE TITLE
Jour de la semaine

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#5]
Ajouter le jour de la semaine à la date des matches.

Ex :
le 10/06 à 21h00 --> le ven 10/06 à 21h00

**Comment by glideblue7** [comment]
Le nom du jour complet est un peu lourd, est il possible de le mettre sur 3 caractères ?
De plus, peut on supprimer "le" devant le jour, pour alléger un peu l'affichage ?
Sachant que dans cette compétition, les horaires des matches sont tjs à heure fixe, peut-on également supprimer le "00" des minutes après le h de l'heure : 21h00 --> 21h
Et "06" et "07" des mois de juin et juillet en "6" et "7" ?
Et remplacer le "à" par une virgule.

Ce qui donnerait au final :
le vendredi 10/06 à 21h00
-->
ven 10/6, 21h

**Comment by johanpoirier** [comment]
J'aime bien le jour complet. Je ferai les autres modifications par contre.
