### ISSUE TITLE
Modifier nom pays

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#57]
RI Iran en Iran
République de Corée en Corée du Sud

(la forme longue de ces 2 pays fait notion à la "politique" et je trouve que ça n'a pas lieu d'être ici)

**Comment by johanpoirier** [comment]
Corée : http://fr.fifa.com/worldcup/teams/team=43822/index.html

Iran : http://fr.fifa.com/worldcup/teams/team=43817/index.html

J'ai pris tous les noms officiels de la FIFA.

**Comment by glideblue7** [comment]
Je sais bien, mais je trouve cela inapproprié quand même. Et selon moi une erreur de la part de la FIFA. Soit on utilise la forme longue pour tous les pays, auquel cas ne plus dire France ou Allemagne mais République française et République fédérale d'Allemagne. Ou alors utiliser la forme courte pour tous les pays. Ce que je propose ici par simplification.

https://fr.wikipedia.org/wiki/Allemagne

https://fr.wikipedia.org/wiki/France

https://fr.wikipedia.org/wiki/Cor%C3%A9e_du_Sud

https://fr.wikipedia.org/wiki/Iran
