### ISSUE TITLE
Mail chgt de mot de passe

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#58]
Dans l'objet du mail et dans la signature figure Euro2016, à modifier par CDM2018

**Comment by johanpoirier** [comment]
C'est fait. Tous les mots de passes ont été remis à 0 par contre (ils sont plus sécurisés si jamais quelqu'un accède à la base de données).
Il faudra aller sur `J'ai oubié mon mot de passe` pour en avoir un nouveau.

**Comment by glideblue7** [comment]
Apparemment, la signature "L'équipe EURO2016" figure toujours dans le mail que l'on reçoit lorsque l'on tente de récupérer son login.
