### ISSUE TITLE
Accès pronostics autres joueurs (pour un admin)

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#6]
Lorsque je clique sur Johan Poirier ou Cyril Poirier, j'accède à la page des pronostics de : "Ab Benlau" ??!! Du moins c'est ce qui s'affiche en haut, mais les pronostics en dessous ont bien l'air d'être ceux de Cyril ou Johan car différents selon la page.

**Comment by johanpoirier** [comment]
Corrigé.
