### ISSUE TITLE
Limitation du nombre de buts possibles?

### ISSUE THREAD

**Issue by flanker1** [johanpoirier/bet4soccer#64]
Je pense qu'il y aura toujours des petits rigolos pour mettre un score de 10000-0 pour fausser la moyenne du nombre de buts.
Limite à 11 buts?

**Comment by flanker1** [comment]
C'est pour cela que j'ai mis 11!!
Mais on peut mettre 15, ça devrait être OK pour tout le monde

**Comment by johanpoirier** [comment]
Bon j'ai fait les 2 finalement :
 - limite à 20
 - calcul médian pour afficher le score moyen
