### ISSUE TITLE
En passant sur les drapeaux, le classement FIFA est "1" pour toutes les équipes

### ISSUE THREAD

**Issue by flanker1** [johanpoirier/bet4soccer#68]
![image](https://user-images.githubusercontent.com/14201181/40361586-22f332c8-5dca-11e8-8839-84e666f7a89e.png)

**Comment by johanpoirier** [comment]
Je ne connais pas le classement FIFA des équipes.
Peux-tu me faire la liste ?

**Comment by flanker1** [comment]
Classement à la date d'aujourd'hui.

2018-05-22 14:22 GMT+02:00 Johan Poirier <notifications@github.com>:

**Comment by johanpoirier** [comment]
> Classement à la date d'aujourd'hui.

Il est où le classement ?

**Comment by flanker1** [comment]
2018-05-22 15:57 GMT+02:00 Johan Poirier <notifications@github.com>:

**Comment by johanpoirier** [comment]
Corrigé
