### ISSUE TITLE
Logo Euro 2016

### ISSUE THREAD

**Issue by glideblue7** [johanpoirier/bet4soccer#73]
![screenshot_20180610-235646](https://user-images.githubusercontent.com/1861722/41220423-a83c1cfa-6d61-11e8-9d75-999aa31e92c1.png)
Sur la version mobile du site, on voit en fond le titre EURO 2016

**Comment by johanpoirier** [comment]
J'ai vu ça ce WE aussi.

**Comment by johanpoirier** [comment]
Corrigé.
